### ISSUE TITLE
Сбор датасета

### ISSUE THREAD

**Issue by manosh7n** [Zatonskikh/lipNet_russian_edition#1]
Не могли бы вы рассказать как вы собирали датасет, про его количество, про то каким образом обучали сеть, ну и в целом про достигнутые результаты? Заранее спасибо

**Comment by Zatonskikh** [comment]
если еще актуально:
Тут лежат исходники от моего диплома, если нужно, скидывайте почту я туда вышлю сам диплом, вроде в нем есть интересующая вас информация

**Comment by manosh7n** [comment]
manoshin.dm@gmail.com

**Comment by manosh7n** [comment]
Все еще актуально, если что :)
